# Use new trusty images, should yield newer compilers and packages
sudo: false          # false (Docker) or required (own VM)
dist: precise
language: generic

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

    - os: osx
      compiler: gcc
      env: COMPILER=g++


script:
  - g++ --version
  - make CXX=$COMPILER
  - src/hello.out
