# Use new trusty images, should yield newer compilers and packages
sudo: false          # false (Docker) or required (own VM)
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      cache:
        directories:
          - /tmp/texlive
          - $HOME/.texlive
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - LDFLAGS=-static
    - os: osx
      osx_image: xcode10.1
      compiler: gcc
      env:
        - MATRIX_EVAL="softwareupdate -l && brew install gcc@7 && CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

git:
  depth: 100

script:
  - autoreconf -i
  - tinysam_version=$(./git-version-gen .version)
  - mkdir build
  - cd build
  - ../configure CXXFLAGS="-std=c++11" tinysamhostsystemname=${TRAVIS_OS_NAME}
  - make
  - make check
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then make dist; fi
  - make binary-archive
  - ls -R
  - make clean
  - make distcheck CXXFLAGS="-std=c++11"
  - cd ..

after_failure:
  - cat build/test-suite.log

deploy:
  provider: releases
  api_key:
    secure: l91h9nNvZJ9n0r3Sro2RPA9hl2L5bJmQPwEL49iwdn+4vyJyIxMJRjXDT+4gHgX7+FeIIYy08DPfJDPMstO0mgUGIZo/pupa9xtuxRfOMBLHYyrEFP3MiFuVzHbquvLLXEPtVQfgnMJLMUQgPkcaeUTdk4ZbFpnFd98hUI0jFQRWmsN98Ki/p9ev5F8J9nkDo79ZaxATNLujuzjcCEypzbINqhcF2y1w5RVwoGCi8q6dzhrxcnFSXtu/QO0Iq5KB14K7fVaAplAGMlUGhLPOpDoRtTVC+/IHZgS5A99O1+JZw9RL4Xa1hRY2Fp9KXmzBoSywXbN3zhQz8TYLzGvDrOUkpcRjGyVJ8UnGp/Ki5y9C5GxzQF9AOxeEWzkeG8FgmS0V8Onf5rRzkH7XlZdf8CtcOc0BiYWV1jrVTnqCc68oyqZlgG/R9F9uTcs8W4EbFEEiIhrL9FCXq4E0UHQUVIeBa7793nMrrnFjN4D+shM9dlg+biuGHA2yRBLctKvK/uwTVvReZpNZPaD6bUk0V9pw5/39mQQ7AB38QV5bVJeTQmGeO6wL+CjRX2NcWZSmuY25WOY6casImg2YWGX4WYOew7dNVDbUD2o0NNpVCYVNy69W/2xkjAQi0k4tVc+xM9ZByifvyBwkd2j0DGPXirXILFJk6+Z7goD947pOAPk=
  file:
    - build/tiny-sam-${tinysam_version}-${TRAVIS_OS_NAME}.tar.gz
    - build/tiny-sam-${tinysam_version}.tar.gz
    - build/tiny-sam-${tinysam_version}.zip
  skip_cleanup: true
  draft: false
  prerelease: true
  on:
    tags: true
    repo: Sylvie/tiny-sam
