# Use new trusty images, should yield newer compilers and packages
sudo: false          # false (Docker) or required (own VM)
dist: precise
language: generic

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libunittest++-dev
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-fonts-recommended
            - chktex
            - latexmk
          env: COMPILER=g++-5
    - os: osx
      compiler: gcc
      env: COMPILER=g++
      before_install:
        - brew update
        - brew outdated unittest-cpp || brew upgrade unittest-cpp



script:
  - g++ --version
  - make CXX=$COMPILER
  - pwd
  - ls build/
  - build/hello.out
