#---------------------------------#
#    environment configuration    #
#---------------------------------#
# scripts that are called at very beginning, before repo cloning
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# build cache to preserve files/folders between builds
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Program Files\MiKTeX 2.9 -> appveyor.yml
  - C:\Users\appveyor\AppData\Roaming\MiKTeX\2.9 -> appveyor.yml

# scripts that run after cloning repository
install:
  - ps: choco install miktex
  - SET PATH=C:\Program Files\MiKTeX 2.9\miktex\bin\x64;%PATH%
  - ps: initexmf --set-config-value [MPM]AutoInstall=1

#---------------------------------#
#       build configuration       #
#---------------------------------#
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: windows

build_script:
  - SET PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%
  - ps: IF (!(Test-Path VERSION)) {New-Item VERSION -itemtype file}
  - set tinysam_version (bash -c "./git-version-gen .version")
  - echo ${tinysam_version}
  - bash -c "autoreconf -i"
  - mkdir build
  - cd build
  - bash -c "../configure --help"
  - bash -c "../configure tinysamhostsystemname=%PLATFORM%"
  - make.exe
  - make.exe binary-archive
  - ps: .\hello.exe
  - ls -R C:\projects\tiny-sam\

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:

# pushing a single file with "Deployment name" specified
#- path: tiny-sam-%APPVEYOR_REPO_TAG_NAME%-%PLATFORM%.tar.gz

# pushing entire folder as a zip archive
- path: build\tiny-sam-${tinysam_version}-%PLATFORM%

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: /nU7mUteW5yQE7WTvX8WQmsR2/qhQr5p34xBndoB9YfP1pTTLxjFdem3OAsMexyR
    #artifact: tiny-sam-%APPVEYOR_REPO_TAG_NAME%-%PLATFORM%.tar.gz
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true       # deploy on tag push only

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
#on_success:
#- do something

# on build failure
#on_failure:
#- do something

# after build failure or success
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

