#---------------------------------#
#    environment configuration    #
#---------------------------------#
# scripts that run after cloning repository
install:
  - ps: New-Item c:\temp\miktex -itemtype directory
  - ps: cd c:\temp\miktex
  - ps: Start-FileDownload "http://mirrors.ctan.org/systems/win32/miktex/setup/miktexsetup.zip"
  - ps: 7z x miktexsetup.zip
  - ls
  - ps: c:\temp\miktex\miktexsetup.exe --verbose --local-package-repository="c:\temp\miktex\" --package-set=basic download
  - ls
  - ps: c:\temp\miktex\miktexsetup.exe --verbose --local-package-repository="c:\temp\miktex\" --package-set=basic install
  - ls
  - ls -R
  - latexmk

#---------------------------------#
#       build configuration       #
#---------------------------------#
build_script:
  - SET PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
  - mingw32-make.exe
  - ls -R C:\projects\tiny-sam\

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:

# pushing a single file with "Deployment name" specified
- path: src\hello.out
  name: hello-appveyor

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: /nU7mUteW5yQE7WTvX8WQmsR2/qhQr5p34xBndoB9YfP1pTTLxjFdem3OAsMexyR
    artifact: hello-appveyor
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true       # deploy on tag push only

