#---------------------------------#
#    environment configuration    #
#---------------------------------#
# scripts that are called at very beginning, before repo cloning
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# build cache to preserve files/folders between builds
cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Program Files\MiKTeX 2.9 -> appveyor.yml

# scripts that run after cloning repository
install:
  - ps: choco install miktex
  - SET PATH=C:\Program Files\MiKTeX 2.9\miktex\bin\x64;%PATH%
  - ps: initexmf --set-config-value [MPM]AutoInstall=1

#---------------------------------#
#       build configuration       #
#---------------------------------#
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: windows

build_script:
  - SET PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%
  - ps: IF (!(Test-Path VERSION)) {New-Item VERSION -itemtype file}
  - set SUFFIXE_SYS=".exe"
  - mingw32-make.exe
  - mingw32-make.exe dist OSNamePostfix="-%PLATFORM%"
  - ps: build/hello.out
  - ls -R C:\projects\tiny-sam\

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:

# pushing a single file with "Deployment name" specified
- path: tiny-sam-%APPVEYOR_REPO_TAG_NAME%-%PLATFORM%.tar.gz

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  # Deploy to GitHub Releases
  - provider: GitHub
    auth_token:
      secure: /nU7mUteW5yQE7WTvX8WQmsR2/qhQr5p34xBndoB9YfP1pTTLxjFdem3OAsMexyR
    artifact: tiny-sam-%APPVEYOR_REPO_TAG_NAME%-%PLATFORM%.tar.gz
    draft: true
    prerelease: false
    on:
      appveyor_repo_tag: true       # deploy on tag push only

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
#on_success:
#- do something

# on build failure
#on_failure:
#- do something

# after build failure or success
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
